version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=BookStore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superPASS

volumes:
  pg_data: